#!/usr/bin/env python3
"""
Pydantic Schema Validation for Variant Functional Impact Reports

This module defines strict, clinical-grade Pydantic models for validating
variant impact reports generated by the genomic-analyst agent. All outputs
assessing variant biological impact must conform to these models.

Workspace Rule 2 Enforcement: Strict Data Type Output - no natural language allowed.
"""

import json
import sys
from enum import Enum
from typing import List, Optional
from datetime import datetime
from pathlib import Path

from pydantic import BaseModel, Field, field_validator, ConfigDict


# ============================================================================
# ENUMERATIONS - Categorical/Strict Type System
# ============================================================================

class PeakProximityFlag(str, Enum):
    """Categorical: Distance relationship to chromatin accessibility peaks."""
    FAR = "FAR"                        # >50bp from peak boundary
    NEAR = "NEAR"                      # ±50bp from peak boundary
    OVERLAPPING = "OVERLAPPING"        # Within peak region


class RiskCategory(str, Enum):
    """Categorical: Composite pathogenicity risk classification."""
    LOW_RISK = "LOW_RISK"              # Combined risk score < 0.4
    MODERATE_RISK = "MODERATE_RISK"    # Combined risk score 0.4-0.7
    HIGH_RISK = "HIGH_RISK"            # Combined risk score > 0.7


class ValidationStatus(str, Enum):
    """Categorical: Schema and data completeness status."""
    VALID = "VALID"                        # All required data present and valid
    INVALID_SCHEMA = "INVALID_SCHEMA"      # Pydantic validation failed
    DATA_GAP = "DATA_GAP"                  # Some functional tracks unavailable


class AssemblyContext(str, Enum):
    """Categorical: Genomic assembly version (hg38-only in this workspace)."""
    HG38 = "hg38"                          # GRCh38.p14 (required and only allowed)


# ============================================================================
# FLOATING-POINT METRICS - Strictly Bounded Numerical Values
# ============================================================================

class ChromatinImpact(BaseModel):
    """
    Chromatin accessibility disruption metrics.
    
    All scores are bounded to [0.0, 1.0] scale:
    - 0.0 = no disruption detected
    - 1.0 = complete loss of accessibility
    """
    
    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_default=True,
        json_schema_extra={
            "description": "Predicted chromatin disruption metrics for the variant"
        }
    )
    
    disruption_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        decimal_places=4,
        description="Chromatin accessibility disruption magnitude (0.0=none, 1.0=complete loss)"
    )
    
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        decimal_places=4,
        description="Model confidence in disruption prediction (0.0=low, 1.0=high)"
    )
    
    peak_proximity: PeakProximityFlag = Field(
        ...,
        description="Spatial relationship to known chromatin accessibility peaks"
    )
    
    affected_track_count: int = Field(
        ...,
        ge=0,
        description="Number of distinct chromatin marks/tracks disrupted by variant"
    )
    
    @field_validator("disruption_score", "confidence")
    @classmethod
    def validate_score_precision(cls, v: float) -> float:
        """Enforce 4 decimal places on all scores."""
        if v is not None:
            rounded = round(v, 4)
            if abs(v - rounded) > 1e-5:
                raise ValueError(f"Score must have ≤4 decimal places: {v}")
        return v


class ExpressionImpact(BaseModel):
    """
    Gene expression disruption metrics across tissue contexts.
    
    Expression deltas are unbounded log-fold-change values:
    - Negative: decreased expression
    - Positive: increased expression
    - Typical range: [-5.0, +5.0] for biological systems
    """
    
    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_default=True,
        json_schema_extra={
            "description": "Predicted expression change metrics for the variant"
        }
    )
    
    delta_mean_log2fc: float = Field(
        ...,
        description="Mean log-fold-change in expression across tissues (unbounded)"
    )
    
    delta_max_log2fc: float = Field(
        ...,
        description="Maximum absolute log-fold-change across all tissues (unbounded)"
    )
    
    tissues_affected: List[str] = Field(
        ...,
        min_length=1,
        description="List of tissues/cell types showing expression change |delta| > 0.5"
    )
    
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        decimal_places=4,
        description="Model confidence in expression prediction (0.0=low, 1.0=high)"
    )
    
    @field_validator("tissues_affected")
    @classmethod
    def validate_tissue_list(cls, v: List[str]) -> List[str]:
        """Tissue list must be non-empty and contain valid tissue names."""
        if not v:
            raise ValueError("tissues_affected list cannot be empty")
        if len(set(v)) != len(v):
            raise ValueError("tissues_affected contains duplicate entries")
        for tissue in v:
            if not isinstance(tissue, str) or len(tissue) == 0:
                raise ValueError(f"Invalid tissue name: {tissue}")
        return v


class AuditMetadata(BaseModel):
    """
    Data integrity and reproducibility audit information.
    """
    
    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_default=True
    )
    
    input_sha256: str = Field(
        ...,
        pattern=r"^[a-f0-9]{64}$",
        description="SHA256 hash of input variant file (hex, 64 chars)"
    )
    
    execution_duration_seconds: int = Field(
        ...,
        ge=0,
        description="Total execution time in seconds"
    )
    
    data_sources: List[str] = Field(
        ...,
        min_length=1,
        description="List of functional track databases queried (e.g., dnase_hg38, gtex_v8)"
    )
    
    @field_validator("data_sources")
    @classmethod
    def validate_data_sources(cls, v: List[str]) -> List[str]:
        """Data sources must be non-empty and contain valid identifiers."""
        if not v:
            raise ValueError("data_sources list cannot be empty")
        for source in v:
            if not isinstance(source, str) or len(source) == 0:
                raise ValueError(f"Invalid data source: {source}")
        return v


class VariantReportMetadata(BaseModel):
    """
    Report metadata: timing, versioning, identifiers.
    """
    
    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_default=True
    )
    
    analysis_id: str = Field(
        ...,
        min_length=5,
        max_length=100,
        description="Unique identifier for this analysis (e.g., BRCA1-VUS-001_20260602154656)"
    )
    
    variant_id: str = Field(
        ...,
        min_length=3,
        max_length=100,
        description="Clinical variant identifier"
    )
    
    timestamp: datetime = Field(
        ...,
        description="ISO-8601 analysis timestamp"
    )
    
    assembly: AssemblyContext = Field(
        default=AssemblyContext.HG38,
        description="Genomic assembly version (hg38-only)"
    )
    
    schema_version: str = Field(
        default="1.0",
        pattern=r"^\d+\.\d+$",
        description="Schema version for this report (semver format)"
    )
    
    @field_validator("assembly")
    @classmethod
    def enforce_hg38(cls, v: AssemblyContext) -> AssemblyContext:
        """Enforce hg38 assembly - workspace rule."""
        if v != AssemblyContext.HG38:
            raise ValueError(
                f"Only hg38 assembly is permitted in this workspace. Received: {v}"
            )
        return v


class VariantInputMetadata(BaseModel):
    """
    Input analysis parameters.
    """
    
    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_default=True
    )
    
    coordinate: str = Field(
        ...,
        pattern=r"^chr([1-9]|[12][0-9]|3[0-2]|X|Y|M):[0-9]+[ATCG]>[ATCG]$",
        description="Variant coordinate (HGVS format: chrN:positionREF>ALT)"
    )
    
    context_window_kb: int = Field(
        default=1000,
        ge=100,
        le=5000,
        description="Sequence context window in kilobases (default 1000)"
    )
    
    prediction_types: List[str] = Field(
        default=["chromatin_accessibility", "expression_delta"],
        description="Types of predictions performed"
    )


# ============================================================================
# PRIMARY REPORT MODEL - Composite Variant Functional Impact Report
# ============================================================================

class VariantFunctionalImpactReport(BaseModel):
    """
    Top-level variant functional impact report.
    
    This is the primary output schema for the genomic-analyst agent.
    Every field is strictly typed and validated per workspace Rule 2.
    
    No natural language commentary is allowed in this schema.
    """
    
    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_default=True,
        json_schema_extra={
            "title": "Variant Functional Impact Report",
            "description": "Clinical-grade variant impact assessment with strict data types",
            "examples": [
                {
                    "metadata": {
                        "analysis_id": "BRCA1-VUS-001_20260602154656",
                        "variant_id": "BRCA1-VUS-001",
                        "timestamp": "2026-06-02T15:46:56Z",
                        "assembly": "hg38",
                        "schema_version": "1.0"
                    },
                    "input": {
                        "coordinate": "chr17:43044295A>G",
                        "context_window_kb": 1000,
                        "prediction_types": ["chromatin_accessibility", "expression_delta"]
                    },
                    "results": {
                        "chromatin_impact": {
                            "disruption_score": 0.8700,
                            "confidence": 0.9200,
                            "peak_proximity": "OVERLAPPING",
                            "affected_track_count": 3
                        },
                        "expression_impact": {
                            "delta_mean_log2fc": -1.4500,
                            "delta_max_log2fc": -2.3000,
                            "tissues_affected": ["heart", "brain"],
                            "confidence": 0.7800
                        },
                        "combined_risk_score": 0.7100,
                        "risk_category": "HIGH_RISK",
                        "validation_status": "VALID",
                        "missing_tracks": []
                    },
                    "audit": {
                        "input_sha256": "4a3f9d8e2c1b7a5f9e3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1",
                        "execution_duration_seconds": 16,
                        "data_sources": ["dnase_hg38", "gtex_expression_v8"]
                    }
                }
            ]
        }
    )
    
    metadata: VariantReportMetadata = Field(
        ...,
        description="Report metadata: IDs, timestamps, versioning"
    )
    
    input: VariantInputMetadata = Field(
        ...,
        description="Analysis input parameters"
    )
    
    results: dict = Field(
        ...,
        description="Analysis results container"
    )
    
    audit: AuditMetadata = Field(
        ...,
        description="Audit trail: input fingerprint, execution time, data sources"
    )
    
    @field_validator("results")
    @classmethod
    def validate_results_structure(cls, v: dict) -> dict:
        """Validate results dictionary contains required keys."""
        required_keys = {
            "chromatin_impact",
            "expression_impact",
            "combined_risk_score",
            "risk_category",
            "validation_status",
            "missing_tracks"
        }
        
        missing = required_keys - set(v.keys())
        if missing:
            raise ValueError(f"results missing required keys: {missing}")
        
        # Validate chromatin_impact structure
        chromatin = v.get("chromatin_impact", {})
        chromatin_required = {"disruption_score", "confidence", "peak_proximity", "affected_track_count"}
        chromatin_missing = chromatin_required - set(chromatin.keys())
        if chromatin_missing:
            raise ValueError(f"chromatin_impact missing keys: {chromatin_missing}")
        
        # Validate expression_impact structure
        expression = v.get("expression_impact", {})
        expression_required = {"delta_mean_log2fc", "delta_max_log2fc", "tissues_affected", "confidence"}
        expression_missing = expression_required - set(expression.keys())
        if expression_missing:
            raise ValueError(f"expression_impact missing keys: {expression_missing}")
        
        # Validate combined_risk_score bounds
        risk_score = v.get("combined_risk_score")
        if not isinstance(risk_score, (int, float)) or not (0.0 <= risk_score <= 1.0):
            raise ValueError(f"combined_risk_score must be float in [0.0, 1.0], got {risk_score}")
        
        # Validate risk_category
        risk_cat = v.get("risk_category")
        if risk_cat not in ["LOW_RISK", "MODERATE_RISK", "HIGH_RISK"]:
            raise ValueError(f"risk_category must be LOW_RISK, MODERATE_RISK, or HIGH_RISK, got {risk_cat}")
        
        # Validate validation_status
        val_status = v.get("validation_status")
        if val_status not in ["VALID", "INVALID_SCHEMA", "DATA_GAP"]:
            raise ValueError(f"validation_status must be VALID, INVALID_SCHEMA, or DATA_GAP, got {val_status}")
        
        # Validate missing_tracks
        missing_tracks = v.get("missing_tracks", [])
        if not isinstance(missing_tracks, list):
            raise ValueError(f"missing_tracks must be a list, got {type(missing_tracks)}")
        
        return v


# ============================================================================
# CLI VALIDATION SCRIPT
# ============================================================================

def validate_report_file(file_path: str, schema_version: str = "1.0", halt_on_error: bool = True) -> dict:
    """
    Validate a variant report JSON file against the Pydantic schema.
    
    Args:
        file_path: Path to the variant report JSON file
        schema_version: Expected schema version (default: "1.0")
        halt_on_error: Exit with error code on validation failure (default: True)
    
    Returns:
        dict: Validation result with keys:
            - success: bool
            - message: str
            - errors: list of error strings (if any)
            - report: VariantFunctionalImpactReport (if valid)
    """
    
    result = {
        "success": False,
        "message": "",
        "errors": [],
        "report": None
    }
    
    # Step 1: Check file exists
    if not Path(file_path).exists():
        result["message"] = f"File not found: {file_path}"
        result["errors"].append(result["message"])
        return result
    
    # Step 2: Load JSON
    try:
        with open(file_path, "r") as f:
            report_data = json.load(f)
    except json.JSONDecodeError as e:
        result["message"] = f"Invalid JSON: {str(e)}"
        result["errors"].append(result["message"])
        return result
    except Exception as e:
        result["message"] = f"Error reading file: {str(e)}"
        result["errors"].append(result["message"])
        return result
    
    # Step 3: Validate against Pydantic schema
    try:
        report = VariantFunctionalImpactReport(**report_data)
        
        # Additional: Check schema version
        if report.metadata.schema_version != schema_version:
            result["errors"].append(
                f"Schema version mismatch: expected {schema_version}, got {report.metadata.schema_version}"
            )
            result["message"] = "Schema version validation failed"
            return result
        
        result["success"] = True
        result["message"] = f"✓ Report is valid and compliant with schema v{schema_version}"
        result["report"] = report
        
    except Exception as e:
        result["message"] = f"Validation failed: {str(e)}"
        result["errors"].append(str(e))
        
        # Extract detailed errors if available
        if hasattr(e, "errors"):
            for err in e.errors():
                error_msg = f"  - {err['loc']}: {err['msg']}"
                result["errors"].append(error_msg)
    
    return result


def main():
    """
    CLI entry point for validating variant reports.
    
    Usage:
        python validate_pydantic_schema.py --report-file <path> [--schema-version <v>] [--halt-on-error true|false]
    
    Example:
        python validate_pydantic_schema.py --report-file data/reports/BRCA1-VUS-001.json --schema-version 1.0 --halt-on-error true
    """
    
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Validate variant functional impact reports against Pydantic schema"
    )
    parser.add_argument(
        "--report-file",
        required=True,
        help="Path to the variant report JSON file"
    )
    parser.add_argument(
        "--schema-version",
        default="1.0",
        help="Expected schema version (default: 1.0)"
    )
    parser.add_argument(
        "--halt-on-error",
        default="true",
        choices=["true", "false"],
        help="Exit with error code on validation failure (default: true)"
    )
    
    args = parser.parse_args()
    halt_on_error = args.halt_on_error.lower() == "true"
    
    # Validate report
    result = validate_report_file(
        file_path=args.report_file,
        schema_version=args.schema_version,
        halt_on_error=halt_on_error
    )
    
    # Output results
    print("")
    print("=" * 70)
    print("VARIANT REPORT VALIDATION RESULT")
    print("=" * 70)
    print("")
    print(result["message"])
    print("")
    
    if not result["success"]:
        print("VALIDATION ERRORS:")
        for error in result["errors"]:
            print(error)
        print("")
        if halt_on_error:
            sys.exit(1)
    else:
        print("Report Structure:")
        print(f"  Analysis ID: {result['report'].metadata.analysis_id}")
        print(f"  Variant ID:  {result['report'].metadata.variant_id}")
        print(f"  Assembly:    {result['report'].metadata.assembly.value}")
        print(f"  Timestamp:   {result['report'].metadata.timestamp.isoformat()}")
        print("")
        print(f"Risk Category: {result['report'].results['risk_category']}")
        print(f"Risk Score:    {result['report'].results['combined_risk_score']:.4f}")
        print(f"Validation:    {result['report'].results['validation_status']}")
        print("")
        if halt_on_error:
            sys.exit(0)


if __name__ == "__main__":
    main()
